### ISSUE TITLE
Spring Guide recommends to use obsolete method

### ISSUE THREAD

**Issue by imanushin** [spring-guides/gs-rest-service-cors#18]
See document https://spring.io/guides/gs/rest-service-cors/#_enabling_cors

Code below tries to use deprecated WebMvcConfigurerAdapter, instead of inline interface implementation:

```
    @Bean
    public WebMvcConfigurer corsConfigurer() {
        return new WebMvcConfigurerAdapter() {
            @Override
            public void addCorsMappings(CorsRegistry registry) {
                registry.addMapping("/greeting-javaconfig").allowedOrigins("http://localhost:9000");
            }
        };
    }
```

**Comment by imanushin** [comment]
https://jira.spring.io/browse/SPR-16790

**Comment by kaklakariada** [comment]
This should be fixed by #19

**Comment by eskimodev** [comment]
> This should be fixed by #19

Not fixed after almost 1 year, the guide still uses the deprecated WebMvcConfigurerAdapter.

**Comment by kaklakariada** [comment]
#19 was never merged. Maybe one of the maintainers could have a look?
